-- EXCOMERCAFE - tablas para sincronizacion en linea
-- Ejecutar completo en Supabase SQL Editor.

create unique index if not exists ventas_agromercado_local_id_key
on public.ventas_agromercado(local_id);

create table if not exists public.inventario_movimientos (
  id bigint generated by default as identity primary key,
  local_id text,
  fecha date,
  ubicacion text,
  lugar text,
  tipo text,
  referencia text,
  arroz numeric default 0,
  arroz_precocido numeric default 0,
  frijol_1lb numeric default 0,
  frijol_4lb numeric default 0,
  aceite_750ml numeric default 0,
  harina_820grs numeric default 0,
  total numeric default 0,
  observaciones text,
  payload jsonb,
  creado_en timestamptz default now()
);

create unique index if not exists inventario_movimientos_local_id_key
on public.inventario_movimientos(local_id);

alter table public.inventario_movimientos enable row level security;

drop policy if exists "inventario_movimientos_select" on public.inventario_movimientos;
drop policy if exists "inventario_movimientos_insert" on public.inventario_movimientos;
drop policy if exists "inventario_movimientos_update" on public.inventario_movimientos;
drop policy if exists "inventario_movimientos_delete" on public.inventario_movimientos;

create policy "inventario_movimientos_select"
on public.inventario_movimientos for select
to anon
using (true);

create policy "inventario_movimientos_insert"
on public.inventario_movimientos for insert
to anon
with check (true);

create policy "inventario_movimientos_update"
on public.inventario_movimientos for update
to anon
using (true)
with check (true);

create policy "inventario_movimientos_delete"
on public.inventario_movimientos for delete
to anon
using (true);

create table if not exists public.distribucion_tiendona (
  id bigint generated by default as identity primary key,
  local_id text,
  fecha date,
  origen text,
  distrito text,
  municipio text,
  agromercado text,
  arroz numeric default 0,
  arroz_precocido numeric default 0,
  frijol_1lb numeric default 0,
  frijol_4lb numeric default 0,
  aceite_750ml numeric default 0,
  harina_820grs numeric default 0,
  total numeric default 0,
  observaciones text,
  payload jsonb,
  creado_en timestamptz default now()
);

create unique index if not exists distribucion_tiendona_local_id_key
on public.distribucion_tiendona(local_id);

alter table public.distribucion_tiendona enable row level security;

drop policy if exists "distribucion_tiendona_select" on public.distribucion_tiendona;
drop policy if exists "distribucion_tiendona_insert" on public.distribucion_tiendona;
drop policy if exists "distribucion_tiendona_update" on public.distribucion_tiendona;
drop policy if exists "distribucion_tiendona_delete" on public.distribucion_tiendona;

create policy "distribucion_tiendona_select"
on public.distribucion_tiendona for select
to anon
using (true);

create policy "distribucion_tiendona_insert"
on public.distribucion_tiendona for insert
to anon
with check (true);

create policy "distribucion_tiendona_update"
on public.distribucion_tiendona for update
to anon
using (true)
with check (true);

create policy "distribucion_tiendona_delete"
on public.distribucion_tiendona for delete
to anon
using (true);

create table if not exists public.distribucion_cda (
  id bigint generated by default as identity primary key,
  local_id text,
  fecha date,
  origen text,
  distrito text,
  municipio text,
  cda text,
  arroz numeric default 0,
  arroz_precocido numeric default 0,
  frijol_1lb numeric default 0,
  frijol_4lb numeric default 0,
  aceite_750ml numeric default 0,
  harina_820grs numeric default 0,
  total numeric default 0,
  observaciones text,
  payload jsonb,
  creado_en timestamptz default now()
);

create unique index if not exists distribucion_cda_local_id_key
on public.distribucion_cda(local_id);

alter table public.distribucion_cda enable row level security;

drop policy if exists "distribucion_cda_select" on public.distribucion_cda;
drop policy if exists "distribucion_cda_insert" on public.distribucion_cda;
drop policy if exists "distribucion_cda_update" on public.distribucion_cda;
drop policy if exists "distribucion_cda_delete" on public.distribucion_cda;

create policy "distribucion_cda_select"
on public.distribucion_cda for select
to anon
using (true);

create policy "distribucion_cda_insert"
on public.distribucion_cda for insert
to anon
with check (true);

create policy "distribucion_cda_update"
on public.distribucion_cda for update
to anon
using (true)
with check (true);

create policy "distribucion_cda_delete"
on public.distribucion_cda for delete
to anon
using (true);

create table if not exists public.estado_cuadres (
  id bigint generated by default as identity primary key,
  local_id text,
  user_id uuid default auth.uid(),
  tipo text,
  fecha text,
  grupo text,
  payload jsonb,
  creado_en timestamptz default now()
);

alter table public.estado_cuadres
add column if not exists user_id uuid default auth.uid();

create unique index if not exists estado_cuadres_local_id_key
on public.estado_cuadres(local_id);

alter table public.estado_cuadres enable row level security;

drop policy if exists "estado_cuadres_select" on public.estado_cuadres;
drop policy if exists "estado_cuadres_insert" on public.estado_cuadres;
drop policy if exists "estado_cuadres_update" on public.estado_cuadres;
drop policy if exists "estado_cuadres_delete" on public.estado_cuadres;

create policy "estado_cuadres_select"
on public.estado_cuadres for select
to anon
using (true);

create policy "estado_cuadres_insert"
on public.estado_cuadres for insert
to anon
with check (true);

create policy "estado_cuadres_update"
on public.estado_cuadres for update
to anon
using (true)
with check (true);

create policy "estado_cuadres_delete"
on public.estado_cuadres for delete
to anon
using (true);

-- Personas responsables por agromercado
create table if not exists public.personas_sistema (
  id bigint generated by default as identity primary key,
  local_id text,
  nombre text,
  cargo text,
  telefono text,
  agromercado text,
  payload jsonb,
  creado_en timestamptz default now(),
  actualizado_en timestamptz default now()
);

alter table public.personas_sistema
add column if not exists local_id text,
add column if not exists nombre text,
add column if not exists cargo text,
add column if not exists telefono text,
add column if not exists agromercado text,
add column if not exists payload jsonb,
add column if not exists actualizado_en timestamptz default now();

create unique index if not exists personas_sistema_local_id_key
on public.personas_sistema(local_id);

alter table public.personas_sistema enable row level security;

drop policy if exists "personas_sistema_select" on public.personas_sistema;
drop policy if exists "personas_sistema_insert" on public.personas_sistema;
drop policy if exists "personas_sistema_update" on public.personas_sistema;
drop policy if exists "personas_sistema_delete" on public.personas_sistema;

create policy "personas_sistema_select"
on public.personas_sistema for select
to anon, authenticated
using (true);

create policy "personas_sistema_insert"
on public.personas_sistema for insert
to authenticated
with check (true);

create policy "personas_sistema_update"
on public.personas_sistema for update
to authenticated
using (true)
with check (true);

create policy "personas_sistema_delete"
on public.personas_sistema for delete
to authenticated
using (true);

-- Usuarios conectados y chat simple
create table if not exists public.presence_online (
  client_id text primary key,
  nombre text,
  pagina text,
  ultimo_visto timestamptz default now()
);

alter table public.presence_online enable row level security;

drop policy if exists "presence_online_select" on public.presence_online;
drop policy if exists "presence_online_insert" on public.presence_online;
drop policy if exists "presence_online_update" on public.presence_online;
drop policy if exists "presence_online_delete" on public.presence_online;
drop policy if exists "presence_online_auth_select" on public.presence_online;
drop policy if exists "presence_online_auth_insert" on public.presence_online;
drop policy if exists "presence_online_auth_update" on public.presence_online;
drop policy if exists "presence_online_auth_delete" on public.presence_online;

create policy "presence_online_select"
on public.presence_online for select
to anon
using (true);

create policy "presence_online_insert"
on public.presence_online for insert
to anon
with check (true);

create policy "presence_online_update"
on public.presence_online for update
to anon
using (true)
with check (true);

create policy "presence_online_delete"
on public.presence_online for delete
to anon
using (true);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  client_id text,
  nombre text,
  mensaje text,
  creado_en timestamptz default now()
);

alter table public.chat_messages enable row level security;

drop policy if exists "chat_messages_select" on public.chat_messages;
drop policy if exists "chat_messages_insert" on public.chat_messages;
drop policy if exists "chat_messages_update" on public.chat_messages;
drop policy if exists "chat_messages_delete" on public.chat_messages;
drop policy if exists "chat_messages_auth_select" on public.chat_messages;
drop policy if exists "chat_messages_auth_insert" on public.chat_messages;
drop policy if exists "chat_messages_auth_update" on public.chat_messages;
drop policy if exists "chat_messages_auth_delete" on public.chat_messages;

create policy "chat_messages_select"
on public.chat_messages for select
to anon
using (true);

create policy "chat_messages_insert"
on public.chat_messages for insert
to anon
with check (true);

create policy "chat_messages_update"
on public.chat_messages for update
to anon
using (true)
with check (true);

create policy "chat_messages_delete"
on public.chat_messages for delete
to anon
using (true);

-- Historial de respaldos EXCOMERCAFE
create table if not exists public.backup_logs (
  id text primary key,
  fecha text,
  hora text,
  usuario text,
  tipo text,
  tablas_incluidas jsonb default '[]'::jsonb,
  total_registros integer default 0,
  origen text,
  resultado text,
  creado_en timestamptz default now()
);

alter table public.backup_logs enable row level security;

drop policy if exists "backup_logs_select" on public.backup_logs;
drop policy if exists "backup_logs_insert" on public.backup_logs;
drop policy if exists "backup_logs_update" on public.backup_logs;
drop policy if exists "backup_logs_delete" on public.backup_logs;

create policy "backup_logs_select"
on public.backup_logs for select
to anon
using (true);

create policy "backup_logs_insert"
on public.backup_logs for insert
to anon
with check (true);

create policy "backup_logs_update"
on public.backup_logs for update
to anon
using (true)
with check (true);

create policy "backup_logs_delete"
on public.backup_logs for delete
to anon
using (true);

-- =========================================================
-- SEGURIDAD PARA PUBLICAR EN LINEA
-- La app usa usuario + contrasena, pero internamente Supabase
-- Auth necesita un email. Crea cada usuario en Authentication
-- con este formato:
--   usuario@excomercafe.local
-- Ejemplos:
--   admin@excomercafe.local
--   tiendona@excomercafe.local
--   cda@excomercafe.local
-- Marca el email como confirmado y asigna una contrasena.
-- =========================================================

alter table public.presence_online
add column if not exists user_id uuid;

alter table public.chat_messages
add column if not exists user_id uuid default auth.uid(),
add column if not exists privado boolean default false,
add column if not exists destinatario_user_id uuid,
add column if not exists destinatario_client_id text,
add column if not exists destinatario_nombre text;

-- Quitar politicas anon abiertas y dejar solo usuarios autenticados.
do $$
declare
  t text;
  p record;
  tablas text[] := array[
    'ventas_agromercado',
    'inventario_movimientos',
    'distribucion_tiendona',
    'distribucion_cda',
    'estado_cuadres',
    'personas_sistema',
    'backup_logs',
    'backups'
  ];
begin
  foreach t in array tablas loop
    if to_regclass('public.' || t) is not null then
      execute format('alter table public.%I enable row level security', t);

      for p in
        select policyname
        from pg_policies
        where schemaname = 'public' and tablename = t
      loop
        execute format('drop policy if exists %I on public.%I', p.policyname, t);
      end loop;

      execute format('create policy %I on public.%I for select to authenticated using (true)', t || '_auth_select', t);
      execute format('create policy %I on public.%I for insert to authenticated with check (true)', t || '_auth_insert', t);
      execute format('create policy %I on public.%I for update to authenticated using (true) with check (true)', t || '_auth_update', t);
      execute format('create policy %I on public.%I for delete to authenticated using (true)', t || '_auth_delete', t);
    end if;
  end loop;
end $$;

-- Personas debe poder leerse desde el portal publico de vendedores.
drop policy if exists "personas_sistema_auth_select" on public.personas_sistema;
drop policy if exists "personas_sistema_auth_insert" on public.personas_sistema;
drop policy if exists "personas_sistema_auth_update" on public.personas_sistema;
drop policy if exists "personas_sistema_auth_delete" on public.personas_sistema;

create policy "personas_sistema_select"
on public.personas_sistema for select
to anon, authenticated
using (true);

create policy "personas_sistema_insert"
on public.personas_sistema for insert
to authenticated
with check (true);

create policy "personas_sistema_update"
on public.personas_sistema for update
to authenticated
using (true)
with check (true);

create policy "personas_sistema_delete"
on public.personas_sistema for delete
to authenticated
using (true);

-- Presencia: todos los usuarios autenticados pueden ver conectados,
-- pero cada sesion solo mantiene su propia presencia.
drop policy if exists "presence_online_select" on public.presence_online;
drop policy if exists "presence_online_insert" on public.presence_online;
drop policy if exists "presence_online_update" on public.presence_online;
drop policy if exists "presence_online_delete" on public.presence_online;

create policy "presence_online_auth_select"
on public.presence_online for select
to authenticated
using (true);

create policy "presence_online_auth_insert"
on public.presence_online for insert
to authenticated
with check (user_id = auth.uid());

create policy "presence_online_auth_update"
on public.presence_online for update
to authenticated
using (user_id = auth.uid() or user_id is null)
with check (user_id = auth.uid());

create policy "presence_online_auth_delete"
on public.presence_online for delete
to authenticated
using (user_id = auth.uid());

-- Chat: mensajes globales visibles para autenticados; mensajes privados
-- solo para quien envia o quien recibe.
drop policy if exists "chat_messages_select" on public.chat_messages;
drop policy if exists "chat_messages_insert" on public.chat_messages;
drop policy if exists "chat_messages_update" on public.chat_messages;
drop policy if exists "chat_messages_delete" on public.chat_messages;

create policy "chat_messages_auth_select"
on public.chat_messages for select
to authenticated
using (
  coalesce(privado, false) = false
  or user_id = auth.uid()
  or destinatario_user_id = auth.uid()
);

create policy "chat_messages_auth_insert"
on public.chat_messages for insert
to authenticated
with check (coalesce(user_id, auth.uid()) = auth.uid());

create policy "chat_messages_auth_update"
on public.chat_messages for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "chat_messages_auth_delete"
on public.chat_messages for delete
to authenticated
using (user_id = auth.uid());
