-- EXCOMERCAFE - fix para aprobar ventas y funciones del portal
-- Ejecutar completo en Supabase SQL Editor.

-- 1) Ventas oficiales: permitir que usuarios autenticados aprueben/envien a ventas_agromercado.
create table if not exists public.ventas_agromercado (
  id bigint generated by default as identity primary key,
  local_id text,
  fecha date,
  dia text,
  distrito text,
  municipio text,
  agromercado text,
  arroz numeric default 0,
  arroz_precocido numeric default 0,
  frijol_1lb numeric default 0,
  frijol_4lb numeric default 0,
  aceite_750ml numeric default 0,
  harina_820grs numeric default 0,
  inventario_inicial numeric default 0,
  ventas numeric default 0,
  gastos numeric default 0,
  remesa numeric default 0,
  dinero_remesado numeric default 0,
  banco text,
  observaciones text,
  payload jsonb,
  creado_en timestamptz default now()
);

alter table public.ventas_agromercado
add column if not exists local_id text,
add column if not exists fecha date,
add column if not exists dia text,
add column if not exists distrito text,
add column if not exists municipio text,
add column if not exists agromercado text,
add column if not exists arroz numeric default 0,
add column if not exists arroz_precocido numeric default 0,
add column if not exists frijol_1lb numeric default 0,
add column if not exists frijol_4lb numeric default 0,
add column if not exists aceite_750ml numeric default 0,
add column if not exists harina_820grs numeric default 0,
add column if not exists inventario_inicial numeric default 0,
add column if not exists ventas numeric default 0,
add column if not exists gastos numeric default 0,
add column if not exists remesa numeric default 0,
add column if not exists dinero_remesado numeric default 0,
add column if not exists banco text,
add column if not exists observaciones text,
add column if not exists payload jsonb,
add column if not exists creado_en timestamptz default now();

create unique index if not exists ventas_agromercado_local_id_key
on public.ventas_agromercado(local_id);

alter table public.ventas_agromercado enable row level security;

drop policy if exists "ventas_agromercado_select" on public.ventas_agromercado;
drop policy if exists "ventas_agromercado_insert" on public.ventas_agromercado;
drop policy if exists "ventas_agromercado_update" on public.ventas_agromercado;
drop policy if exists "ventas_agromercado_delete" on public.ventas_agromercado;
drop policy if exists "ventas_agromercado_auth_select" on public.ventas_agromercado;
drop policy if exists "ventas_agromercado_auth_insert" on public.ventas_agromercado;
drop policy if exists "ventas_agromercado_auth_update" on public.ventas_agromercado;
drop policy if exists "ventas_agromercado_auth_delete" on public.ventas_agromercado;

create policy "ventas_agromercado_auth_select"
on public.ventas_agromercado for select
to authenticated
using (true);

create policy "ventas_agromercado_auth_insert"
on public.ventas_agromercado for insert
to authenticated
with check (true);

create policy "ventas_agromercado_auth_update"
on public.ventas_agromercado for update
to authenticated
using (true)
with check (true);

create policy "ventas_agromercado_auth_delete"
on public.ventas_agromercado for delete
to authenticated
using (true);

-- 2) Funcion publica para que el portal vea si existe un envio pendiente.
create or replace function public.portal_agromercado_pendiente(p_agromercado text)
returns table (
  pendiente boolean,
  fecha text,
  creado_en timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    exists (
      select 1
      from public.ventas_agromercado_pendientes v
      where v.agromercado = p_agromercado
        and v.estado = 'pendiente'
    ) as pendiente,
    (
      select v.fecha
      from public.ventas_agromercado_pendientes v
      where v.agromercado = p_agromercado
        and v.estado = 'pendiente'
      order by v.creado_en desc
      limit 1
    ) as fecha,
    (
      select v.creado_en
      from public.ventas_agromercado_pendientes v
      where v.agromercado = p_agromercado
        and v.estado = 'pendiente'
      order by v.creado_en desc
      limit 1
    ) as creado_en;
$$;

grant execute on function public.portal_agromercado_pendiente(text) to anon, authenticated;

-- 3) Funcion publica para inventario anterior y mercaderia nueva del portal.
create or replace function public.portal_agromercado_stock(
  p_agromercado text,
  p_fecha date default current_date
)
returns table (
  producto text,
  anterior numeric,
  nuevo numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  prev_payload jsonb;
begin
  select v.payload
    into prev_payload
  from public.ventas_agromercado v
  where v.agromercado = p_agromercado
    and v.fecha < p_fecha
  order by v.fecha desc, v.creado_en desc
  limit 1;

  return query
  with productos(producto, json_key, col_name) as (
    values
      ('arroz', 'arroz', 'arroz'),
      ('precocido', 'precocido', 'arroz_precocido'),
      ('frijol1', 'frijol1', 'frijol_1lb'),
      ('frijol4', 'frijol4', 'frijol_4lb'),
      ('aceite', 'aceite', 'aceite_750ml'),
      ('harina', 'harina', 'harina_820grs')
  ),
  nuevos as (
    select
      coalesce(sum(d.arroz), 0) as arroz,
      coalesce(sum(d.arroz_precocido), 0) as arroz_precocido,
      coalesce(sum(d.frijol_1lb), 0) as frijol_1lb,
      coalesce(sum(d.frijol_4lb), 0) as frijol_4lb,
      coalesce(sum(d.aceite_750ml), 0) as aceite_750ml,
      coalesce(sum(d.harina_820grs), 0) as harina_820grs
    from public.distribucion_tiendona d
    where d.agromercado = p_agromercado
      and d.fecha = p_fecha
  )
  select
    p.producto,
    coalesce((prev_payload->'inventario_final'->>p.json_key)::numeric, 0) as anterior,
    case p.col_name
      when 'arroz' then n.arroz
      when 'arroz_precocido' then n.arroz_precocido
      when 'frijol_1lb' then n.frijol_1lb
      when 'frijol_4lb' then n.frijol_4lb
      when 'aceite_750ml' then n.aceite_750ml
      when 'harina_820grs' then n.harina_820grs
      else 0
    end as nuevo
  from productos p
  cross join nuevos n;
end;
$$;

grant execute on function public.portal_agromercado_stock(text, date) to anon, authenticated;
